spring:
  application:
    name: ecommerce
  config:
    import: optional:classpath:application-payment.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: admin
    password: admindev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: admindev
  bucket: ecommerce

tosspayments:
  base-url: https://api.tosspayments.com
